# Generated by Django 4.1.5 on 2023-02-11 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Derecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classification', models.CharField(choices=[('automobile', 'automóvil'), ('motorcycle', 'moto')], max_length=30)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sale_value', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('national_register', models.CharField(choices=[('rna', 'RNA'), ('rnc', 'RNC')], max_length=30)),
                ('classification', models.CharField(choices=[('automobile', 'automóvil'), ('motorcycle', 'moto')], max_length=30)),
                ('vigencia', models.DateTimeField()),
                ('derechos', models.ManyToManyField(to='transactions.derecho')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('comment', models.TextField()),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.asesor')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.cliente')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.tramite')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.vehiculo')),
            ],
        ),
    ]
