# Generated by Django 4.1.5 on 2023-02-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaccion_assessor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='document_number',
            field=models.IntegerField(),
        ),
    ]
