# Generated by Django 4.1.5 on 2023-02-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_cliente_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='num_documento',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
