# Generated by Django 4.1.5 on 2023-02-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_vehiculo_vehicle_type_vehiculo_classification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='client',
            new_name='cliente',
        ),
    ]
