# Generated by Django 4.1.5 on 2023-01-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='productos',
            field=models.ManyToManyField(to='invoice.product'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
