# Generated by Django 4.1.5 on 2023-02-04 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoice_title_invoice_iva_invoice_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 11, 13, 42, 21, 606342, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='iva',
            field=models.IntegerField(default=16),
        ),
    ]
