# Generated by Django 4.1.5 on 2023-02-10 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_due_at_alter_invoice_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Derecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classification', models.CharField(choices=[('automobile', 'automóvil'), ('motorcycle', 'moto')], max_length=30)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sale_value', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('national_register', models.CharField(choices=[('RNA', 'RNA'), ('RNC', 'RNC')], max_length=30)),
                ('classification', models.CharField(choices=[('automobile', 'automóvil'), ('motorcycle', 'moto')], max_length=30)),
                ('vigencia', models.DateTimeField()),
                ('derechos', models.ManyToManyField(to='invoice.derecho')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('comment', models.TextField()),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.asesor')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.cliente')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.tramite')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product_sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_sale',
            name='sale',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_Sale',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.vehiculo'),
        ),
    ]
