# Generated by Django 4.1.5 on 2023-02-01 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_productos_alter_invoice_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maker',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 8, 12, 1, 8, 286331, tzinfo=datetime.timezone.utc)),
        ),
    ]
