# Generated by Django 4.1.5 on 2023-02-01 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_product_maker_alter_invoice_due_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 8, 18, 20, 11, 538729, tzinfo=datetime.timezone.utc)),
        ),
    ]
