# Generated by Django 4.1.5 on 2023-02-01 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoice_due_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 8, 18, 45, 17, 537004, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
