# Generated by Django 4.1.5 on 2023-02-02 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_due_at_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='productos',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 9, 12, 51, 53, 121172, tzinfo=datetime.timezone.utc)),
        ),
    ]
