# Generated by Django 4.1.5 on 2023-02-02 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_rename_productos_invoice_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='payment_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 9, 12, 52, 19, 545639, tzinfo=datetime.timezone.utc)),
        ),
    ]
