# Generated by Django 4.1.5 on 2023-02-02 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_rename_payment_status_invoice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 9, 23, 37, 25, 571831, tzinfo=datetime.timezone.utc)),
        ),
    ]
